name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  rundoc:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
      - run: gem install rundoc
      - run: rundoc build --path source.md
      - run: ls
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: running rundoc
          branch: ${{ github.event.head_commit.timestamp }}
          create_branch: true
