name: run-rundoc
run-name: running rundoc on tutorials
on:
  push:
    branches:
      - tutorials
      - mac
  schedule:
    # This schedule triggers the workflow at 00:00 every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  rundoc-mac:
    runs-on: macos-12
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true # do run 'bundle install' and cache
          working-directory: .rundoc-workspace
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha
      # [CONFIG] here for the path of what we want to generate
      - run: brew install buildpacks/tap/pack
      - run: bundle exec rundoc build --path ../tutorials/src/ruby/rundoc.md
        working-directory: .rundoc-workspace
      # [CONFIG] then here move and rename README.md to the appropriate place
      - run: echo "NOW=$(date +'rundoc-macos/%s')" >> $GITHUB_ENV
      - run: echo "HUMAN_DATE=$(date +'MacOS update tutorials - %Y %b %d')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.NOW }}
          base: main
          commit-message: run rundoc
          title: ${{ env.HUMAN_DATE }}
          body: "generated by the [run-rundoc macos github action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
