name: run-rundoc
run-name: running rundoc on tutorials
on:
  schedule:
    # This schedule triggers the workflow at 00:00 every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  rundoc-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true # do run 'bundle install' and cache
          working-directory: .rundoc-workspace
      # [CONFIG] here for the path of what we want to generate
      - uses: buildpacks/github-actions/setup-pack@v5.7.1
      - run: bundle exec rundoc ../tutorials/src/ruby/rundoc.md --on-success-dir ../tutorials/output --on-failure-dir ../tutorials/fail --force
        working-directory: .rundoc-workspace
        continue-on-error: true
      - run: rm -rf ruby-getting-started
        working-directory: tutorials/output
        continue-on-error: true
      # [CONFIG] then here move and rename README.md to the appropriate place
      - run: echo "TITLE=$(date +'Update tutorials - %Y %b %d')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: rundoc-update
          base: main
          commit-message: execute rundoc on ruby tutorial
          title: ${{ env.TITLE }}
          body: "generated by the [run-rundoc linux github action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
